# Generated by Django 4.2.29 on 2026-08-08 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, help_text='m²', max_digits=12, null=True)),
                ('total_wall_length', models.DecimalField(blank=True, decimal_places=2, help_text='metr', max_digits=12, null=True)),
                ('total_material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='UZS', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Hisoblanmoqda'), ('completed', 'Tayyor'), ('failed', 'Xatolik')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('wall', 'Devor materiali'), ('concrete', 'Beton'), ('cement', 'Sement'), ('sand', 'Qum'), ('gravel', "Shag'al"), ('rebar', 'Armatura'), ('other', 'Boshqa')], default='other', max_length=30)),
                ('unit', models.CharField(help_text='Masalan: dona, kg, tonna, m³, metr', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('active', 'Faol'), ('completed', 'Tugallangan'), ('archived', 'Arxivlangan')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(max_length=30)),
                ('source', models.CharField(blank=True, help_text="Narx manbasi yoki do'kon nomi", max_length=200)),
                ('region', models.CharField(blank=True, help_text='Masalan: Toshkent', max_length=100)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='main.material')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='drawings/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Yuklangan'), ('processing', 'Hisoblanmoqda'), ('processed', 'Tayyor'), ('failed', 'Xatolik')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='main.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('unit', models.CharField(max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.calculation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculation_items', to='main.material')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='calculation',
            name='drawing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='main.drawing'),
        ),
    ]
